export const defaultOffers = [
  {
    id: 'offer-facturas',
    title: 'Docena de facturas',
    business: 'Panaderia La Esquina',
    category: 'Panaderia',
    section: 'Liceo 2da',
    price: '$4.200',
    expires: '3 dias',
    address: 'Av. Alfonsina Storni 1840',
    whatsapp: '3515551840',
    reference: 'Frente a la plaza chica de Liceo 2da',
    hours: 'Lun a sab - 8:00 a 20:30',
    description: 'Promo disponible para retiro por mostrador. Se puede reservar por WhatsApp.',
    tone: 'amber',
    image: 'bread',
    open: true,
    distance: '450 m',
    saves: 18,
    highlight: 'Retiro inmediato',
  },
  {
    id: 'offer-milanesa',
    title: 'Combo milanesa + papas',
    business: 'Lo de Meli',
    category: 'Comida',
    section: 'Liceo Procrear',
    price: '$7.900',
    expires: '4 dias',
    address: 'Mza 18 Casa 6 - Liceo Procrear',
    reference: 'A dos cuadras del ingreso principal',
    hours: 'Jue a dom - 20:00 a 00:30',
    description: 'Milanesa grande con papas. Sale por tandas, conviene reservar temprano.',
    tone: 'orange',
    image: 'milanesa',
    open: true,
    distance: '700 m',
    saves: 31,
    highlight: 'Ideal cena',
  },
  {
    id: 'offer-verduras',
    title: 'Bolson verduras',
    business: 'Verdu Norte',
    category: 'Verduleria',
    section: 'Liceo 1ra',
    price: '$8.900',
    expires: '3 dias',
    address: 'Ruben Dario 2265',
    reference: 'Cerca de la parada del colectivo',
    hours: 'Lun a sab - 9:00 a 21:00',
    description: 'Bolson armado con verduras de estacion. Consultar envio dentro del barrio.',
    tone: 'green',
    image: 'veggie',
    open: true,
    distance: '900 m',
    saves: 22,
    highlight: 'Envio barrio',
  },
  {
    id: 'offer-carnes',
    title: 'Asado cortado para el finde',
    business: 'Carnes Nico',
    category: 'Carniceria',
    section: 'Liceo 3ra',
    price: '$18.500',
    expires: '4 dias',
    address: 'Clementina Quenel 1512',
    reference: 'Local sobre esquina',
    hours: 'Lun a sab - 8:30 a 13:30',
    description: 'Corte armado para parrilla chica. Stock limitado, se reserva por WhatsApp.',
    tone: 'red',
    image: 'meat',
    open: false,
    distance: '1.4 km',
    saves: 9,
    highlight: 'Stock limitado',
  },
  {
    id: 'offer-despensa',
    title: 'Yerba + azucar + fideos',
    business: 'Despensa Solcito',
    category: 'Despensa',
    section: 'Liceo Procrear',
    price: '$8.400',
    expires: '3 dias',
    address: 'Agustina Andrade 1930',
    reference: 'Al lado del kiosco 24',
    hours: 'Todos los dias - 8:00 a 23:00',
    description: 'Combo de almacen para salir del paso. Marcas sujetas a stock del dia.',
    tone: 'yellow',
    image: 'pantry',
    open: true,
    distance: '600 m',
    saves: 14,
    highlight: 'Almacen',
  },
  {
    id: 'offer-ferreteria',
    title: 'Kit tarugos + mecha',
    business: 'Ferreteria Avenida',
    category: 'Ferreteria',
    section: 'Liceo 2da',
    price: '$3.200',
    expires: '3 dias',
    address: 'Av. Alfonsina Storni 2104',
    reference: 'Entre Julio A. Roca y Cuneo Dardo',
    hours: 'Lun a sab - 8:30 a 19:30',
    description: 'Kit para arreglos chicos del hogar. Se puede pedir por WhatsApp y retirar.',
    tone: 'teal',
    image: 'tools',
    open: false,
    distance: '1.1 km',
    saves: 7,
    highlight: 'Para arreglos',
  },
  {
    id: 'offer-plomero',
    title: 'Cambio de cuerito',
    business: 'Plomero Marcelo',
    category: 'Servicios',
    section: 'Liceo 1ra',
    price: 'Desde $6.000',
    expires: '4 dias',
    address: 'Atiende en todo Barrio Liceo',
    reference: 'Coordina por WhatsApp segun urgencia',
    hours: 'Lun a sab - 9:00 a 18:00',
    description: 'Servicio chico de plomeria para perdidas simples. Consulta foto por WhatsApp.',
    tone: 'blue',
    image: 'tools',
    open: true,
    distance: 'a domicilio',
    saves: 11,
    highlight: 'A domicilio',
  },
  {
    id: 'offer-belleza',
    title: 'Perfilado de cejas',
    business: 'Cami Beauty',
    category: 'Belleza',
    section: 'Liceo Procrear',
    price: '$3.500',
    expires: '4 dias',
    address: 'Liceo Procrear - sector centro',
    reference: 'Atencion con turno previo',
    hours: 'Mar a sab - 10:00 a 19:00',
    description: 'Perfilado de cejas. Consultar horarios disponibles para hoy.',
    tone: 'pink',
    image: 'beauty',
    open: true,
    distance: '500 m',
    saves: 16,
    highlight: 'Con turno',
  },
]

export const defaultBusinesses = [
  {
    id: 'business-panaderia',
    name: 'Panaderia La Esquina',
    category: 'Panaderia',
    section: 'Liceo 2da',
    address: 'Av. Alfonsina Storni 1840',
    hours: 'Lun a sab - 8:00 a 20:30',
    tone: 'amber',
    image: 'bread',
    open: true,
    rating: '4.8',
    followers: 124,
    verified: true,
    delivery: 'Retiro y envio',
    hasDelivery: true,
    orderHours: 'Pedidos 8:00 a 20:00',
    deliveryZone: 'Envio en Liceo 1ra y 2da',
    distance: '450 m',
    menu: [
      { name: 'Docena de facturas', price: '$4.200' },
      { name: 'Pan casero', price: '$1.600' },
      { name: 'Criollos', price: '$2.300' },
      { name: 'Tortitas negras', price: '$2.000' },
      { name: 'Budin casero' },
    ],
  },
  {
    id: 'business-meli',
    name: 'Lo de Meli',
    category: 'Comida',
    section: 'Liceo Procrear',
    address: 'Mza 18 Casa 6',
    whatsapp: '3515551806',
    hours: 'Jue a dom - 20:00 a 00:30',
    tone: 'orange',
    image: 'milanesa',
    open: true,
    rating: '4.9',
    followers: 210,
    verified: true,
    delivery: 'Pedido por WhatsApp',
    hasDelivery: true,
    orderHours: 'Pedidos 20:00 a 00:30',
    deliveryZone: 'Delivery nocturno en Procrear',
    distance: '700 m',
    menu: [
      { name: 'Milanesa + papas', price: '$7.900' },
      { name: 'Sanguche de milanesa', price: '$6.800' },
      { name: 'Tarta del dia', price: '$5.200' },
      { name: 'Empanadas docena', price: '$9.600' },
      { name: 'Menu infantil', price: '$4.400' },
    ],
  },
  {
    id: 'business-verdu',
    name: 'Verdu Norte',
    category: 'Verduleria',
    section: 'Liceo 1ra',
    address: 'Ruben Dario 2265',
    whatsapp: '3515552265',
    hours: 'Lun a sab - 9:00 a 21:00',
    tone: 'green',
    image: 'veggie',
    open: true,
    rating: '4.7',
    followers: 98,
    verified: true,
    delivery: 'Envio barrio',
    hasDelivery: true,
    orderHours: 'Pedidos 9:00 a 21:00',
    deliveryZone: 'Envio en todo Liceo',
    distance: '900 m',
    menu: [
      { name: 'Bolson verduras', price: '$8.900' },
      { name: 'Fruta seleccionada', price: '$3.500' },
      { name: 'Envio barrio', price: '$900' },
      { name: 'Huevos maples' },
      { name: 'Verdura para sopa', price: '$2.800' },
    ],
  },
  {
    id: 'business-despensa',
    name: 'Despensa Solcito',
    category: 'Despensa',
    section: 'Liceo Procrear',
    address: 'Agustina Andrade 1930',
    whatsapp: '3515551930',
    hours: 'Todos los dias - 8:00 a 23:00',
    tone: 'yellow',
    image: 'pantry',
    open: true,
    rating: '4.7',
    followers: 156,
    verified: true,
    delivery: 'Envio por compra minima',
    hasDelivery: true,
    orderHours: 'Pedidos 9:00 a 22:30',
    deliveryZone: 'Envio cerca de Procrear',
    distance: '600 m',
    menu: [
      { name: 'Combo almacen', price: '$8.400' },
      { name: 'Gaseosa 2.25L', price: '$2.600' },
      { name: 'Pan lactal', price: '$2.100' },
      { name: 'Leche larga vida', price: '$1.450' },
      { name: 'Yerba 1kg', price: '$3.900' },
    ],
  },
  {
    id: 'business-ferreteria',
    name: 'Ferreteria Avenida',
    category: 'Ferreteria',
    section: 'Liceo 2da',
    address: 'Av. Alfonsina Storni 2104',
    whatsapp: '3515552104',
    hours: 'Lun a sab - 8:30 a 19:30',
    tone: 'teal',
    image: 'tools',
    open: false,
    rating: '4.6',
    followers: 64,
    verified: false,
    delivery: 'Retiro en local',
    hasDelivery: false,
    orderHours: 'Pedidos 8:30 a 19:00',
    deliveryZone: 'Solo retiro por mostrador',
    distance: '1.1 km',
    menu: [
      { name: 'Kit tornillos', price: '$3.200' },
      { name: 'Cinta aisladora', price: '$1.200' },
      { name: 'Mechas desde', price: '$2.000' },
      { name: 'Llaves copia' },
      { name: 'Pegamento universal', price: '$1.800' },
    ],
  },
]
